# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Generate Build"
  lane :build do
    gradle(
      task: "assemble",
      build_type: "debug"
    )

    firebase_app_distribution(
                app: "1:755890961033:android:fcb6b362b54187e6966458",
                testers: "kbmaradiya@gmail.com,krupa.maradiya@mindbowser.com",
                release_notes_file: "releaseNote.txt",
                firebase_cli_token: "1//0g6MRk-Ov5Q55CgYIARAAGBASNwF-L9IrrpH9z-A0TzYgl0hPj4QmvxAFi83JwVFn6t3yCwA9kED79VcJQXXBr9w3bvxUlYezsg0"
            )

  end
end
